### ISSUE TITLE
Planner needs a new repository for the testPlans in tng-rep, local or both

### ISSUE THREAD

**Issue by andreoug** [sonata-nfv/tng-vnv-planner#40]
Planner might need a new repository for the testPlans in tng-rep, but till then we will change the `/tpr` endpoint of tng-rep to the old classic `/trr`, which must is the testResuts repository, hopefully.

**Comment by jbonnet** [comment]
@allemaos We had agreed a long time ago after the Vigo meeting (12th Feb 2019) that the Planner would need to keep state, so that it could answer the GKs queries. Since this storage is totally managed by the Planner, it should be kept within the micor-service's borders, that is, we should not use the repository for that. The technical reason behind this decision is the planner will access this storage often to update the status of the execution of the plan, while the repository is a 'write once/read many' kind of storage.

**Comment by andreoug** [comment]
excellent. And so it will be.
therefore, a) not repository for testPlans. only DB storage. b) the rest call with tng-repo with be totally removed.
